### ISSUE TITLE
bump Jinja library requirement to 2.11.0

### ISSUE THREAD

**Issue by kent007** [mattrobenolt/jinja2-cli#94]
jinja-cli crashes unless the Jinja library dependency is version 2.11.0. Currently the package wants "any"

using Jinja2 version 2.10.3, you get
```
from jinja2 import ChainableUndefined
ImportError: cannot import name 'ChainableUndefined'
```

ChainableUndefined was added in Jinja2 [v2.11.0](https://jinja.palletsprojects.com/en/2.11.x/changelog/#version-2-11-0)

**Comment by kent007** [comment]
I did a bit more digging,

Installing jinja-cli (the wheel build fails on my WSL instance, but it still installs via setup.py)
```
Building wheels for collected packages: jinja-cli
  Building wheel for jinja-cli (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/kent/myvenv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-v8ijcfi8/jinja-cli/setup.py'"'"'; __file__='"'"'/tmp/pip-install-v8ijcfi8/jinja-cli/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-6s0lgpvn
       cwd: /tmp/pip-install-v8ijcfi8/jinja-cli/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for jinja-cli
  Running setup.py clean for jinja-cli
Failed to build jinja-cli
Installing collected packages: jinja-cli
    Running setup.py install for jinja-cli ... done
``` 

I deliberately downgraded Jinja2 to 2.10.3, here's the output of pip freeze
```
(myvenv) kent@WSL:~$ pip freeze
argparse-ext==1.4.0
jinja-cli==1.2.0
Jinja2==2.10.3
MarkupSafe==2.0.1
PyYAML==5.4.1
xmltodict==0.12.0
```

then running jinja-cli
```
jinja --help
Traceback (most recent call last):
  File "/home/kent/myvenv/bin/jinja", line 11, in <module>
    load_entry_point('jinja-cli==1.2.0', 'console_scripts', 'jinja')()
  File "/home/kent/myvenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/kent/myvenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/kent/myvenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/kent/myvenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kent/myvenv/lib/python3.8/site-packages/jinja_cli/__main__.py", line 7, in <module>
    from jinja2 import ChainableUndefined
ImportError: cannot import name 'ChainableUndefined' from 'jinja2' (/home/kent/myvenv/lib/python3.8/site-packages/jinja2/__init__.py)
```

when I bump the Jinja version back up to 2.11.0, it doesn't error out.

Out of curiosity, I installed `wheel` and rebuilt on a new venv. Same problem when I force downgrade Jinja2 to 2.10.3
```
(myvenv) kent@LP-KMCDONOU-W10:~$ jinja --help
Traceback (most recent call last):
  File "/home/kent/myvenv/bin/jinja", line 5, in <module>
    from jinja_cli.__main__ import main
  File "/home/kent/myvenv/lib/python3.8/site-packages/jinja_cli/__main__.py", line 7, in <module>
    from jinja2 import ChainableUndefined
ImportError: cannot import name 'ChainableUndefined' from 'jinja2' (/home/kent/myvenv/lib/python3.8/site-packages/jinja2/__init__.py)
```

am I missing something obvious here?

**Comment by mattrobenolt** [comment]
Yeah, this project isn't `jinja-cli`, this is `jinja2-cli`.

I'm guessing you're looking for: https://github.com/cykerway/jinja-cli/blob/master/jinja_cli/__main__.py#L7

Which is a much lesser known variant than the one here and has the bug you're pointing out.

**Comment by kent007** [comment]
...yeah, that'll do it.

Thanks for the link, might as well bring this up with the correct project.
